cli-source = "morpheapp/morphe-cli"
cli-version = "dev"
patches-source = "anddea/revanced-patches"
patches-version = "dev"

[YouTube]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
arch = "arm64-v8a"
patcher-args = "-OpackageNameYouTube=com.youtube.android"

[Music]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
github-release-dlurl = "https://github.com/AzyrRuthless/YTYTM-APK/releases/latest"
arch = "arm64-v8a"
# patcher-args = "-OpackageNameYouTubeMusic=com.youtube.music.android"

[Reddit]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
arch = "arm64-v8a"
# patcher-args = "-OpackageNameReddit=com.reddit.android"
