cli-source = "morpheapp/morphe-cli"
cli-version = "dev"
patches-source = "crimera/piko"
patches-version = "dev"

[Twitter]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
arch = "arm64-v8a"
# patcher-args = "-OpackageNameTwitter=com.twitter.android"
